"""add the user Role to the users table

Revision ID: 413b701a0b77
Revises: ca1c106f7901
Create Date: 2020-10-01 20:17:53.800039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '413b701a0b77'
down_revision = 'ca1c106f7901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'Role')
    # ### end Alembic commands ###
