"""Initial migration

Revision ID: b7a363bd9a29
Revises: 
Create Date: 2020-10-01 18:55:00.246642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a363bd9a29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('toDoList', sa.String(), nullable=True),
    sa.Column('phoneNumber', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('Address', sa.String(), nullable=True),
    sa.Column('donationsReceived', sa.Integer(), nullable=True),
    sa.Column('accountDetails', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donor', sa.String(), nullable=True),
    sa.Column('donorAnonimity', sa.Boolean(), nullable=True),
    sa.Column('Donee', sa.String(), nullable=True),
    sa.Column('Amount', sa.Integer(), nullable=True),
    sa.Column('Date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('accountdetails', sa.Integer(), nullable=True),
    sa.Column('donation_frequency', sa.Boolean(), nullable=True),
    sa.Column('reminding_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beneficiaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('inventory', sa.Integer(), nullable=True),
    sa.Column('stories', sa.String(), nullable=True),
    sa.Column('Charity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Charity'], ['charity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beneficiaries')
    op.drop_table('users')
    op.drop_table('donors')
    op.drop_table('donations')
    op.drop_table('charity')
    # ### end Alembic commands ###
