"""update the cahrity model

Revision ID: fd2a02e872f3
Revises: 8caf5be199ed
Create Date: 2020-09-29 22:37:51.004545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2a02e872f3'
down_revision = '8caf5be199ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charity', sa.Column('Address', sa.String(), nullable=True))
    op.add_column('charity', sa.Column('accountDetails', sa.Integer(), nullable=True))
    op.add_column('charity', sa.Column('donationsReceived', sa.Integer(), nullable=True))
    op.add_column('charity', sa.Column('email', sa.String(), nullable=True))
    op.add_column('charity', sa.Column('phoneNumber', sa.String(), nullable=True))
    op.add_column('charity', sa.Column('toDoList', sa.String(), nullable=True))
    op.drop_column('charity', 'Todolist')
    op.drop_column('charity', 'Donations_received')
    op.drop_column('charity', 'Account_details')
    op.drop_column('charity', 'Contacts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charity', sa.Column('Contacts', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('charity', sa.Column('Account_details', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('charity', sa.Column('Donations_received', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('charity', sa.Column('Todolist', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('charity', 'toDoList')
    op.drop_column('charity', 'phoneNumber')
    op.drop_column('charity', 'email')
    op.drop_column('charity', 'donationsReceived')
    op.drop_column('charity', 'accountDetails')
    op.drop_column('charity', 'Address')
    # ### end Alembic commands ###
